/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
export declare function encodeHeaders(headers: Array<Array<string>>): Buffer
export declare function decodeHeaders(block: Buffer): Array<Array<string>>
export interface H3Request {
  method: string
  path: string
  headers: Array<Array<string>>
  body: Buffer
}
export interface H3Response {
  status: number
  headers: Array<Array<string>>
  body: string
}
/**
 * Start a native HTTP/3 server. The callback handles each request.
 * Blocks until the server stops.
 */
export declare function serve(port: number, handler: (req: H3Request) => H3Response): void
