/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
export declare function encodeHeaders(headers: Array<Array<string>>): Buffer
export declare function decodeHeaders(block: Buffer): Array<Array<string>>
export interface H3Request {
  method: string
  path: string
  headers: Array<Array<string>>
  body: Buffer
}
export interface H3Response {
  status: number
  headers: Array<Array<string>>
  body: string
}
/**
 * Start a native HTTP/3 server. The callback handles each request.
 * Blocks until the server stops.
 */
export declare function serve(port: number, handler: (req: H3Request) => H3Response): void
/** Response from an HTTP/3 fetch. */
export interface FetchResponse {
  status: number
  headers: Array<Array<string>>
  body: string
  /** QUIC connect time in milliseconds */
  connectMs: number
  /** Total request time in milliseconds */
  totalMs: number
}
/** Options for fetch. */
export interface FetchOptions {
  method?: string
  body?: string
  headers?: Array<Array<string>>
}
/**
 * HTTP/3 fetch — like fetch() but over QUIC. Returns a Promise.
 *
 * Usage:
 *   const resp = await h3fetch('https://localhost:4433/health');
 *   console.log(resp.status, resp.body);
 *
 *   const resp = await h3fetch('https://localhost:4433/echo', {
 *     method: 'POST',
 *     body: JSON.stringify({ hello: 'world' }),
 *   });
 */
export declare function h3Fetch(url: string, options?: FetchOptions | undefined | null): Promise<FetchResponse>
