"""Type stubs for nhttp3."""

from typing import Optional, Tuple, Any

__version__: str

class Config:
    max_idle_timeout: float
    initial_max_data: int
    initial_max_stream_data_bidi_local: int
    initial_max_stream_data_bidi_remote: int
    initial_max_stream_data_uni: int
    initial_max_streams_bidi: int
    initial_max_streams_uni: int
    enable_0rtt: bool
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...

class Endpoint:
    @staticmethod
    async def bind(host: str, port: int, config: Optional[Config] = None) -> "Endpoint": ...
    async def accept(self) -> "Connection": ...
    async def connect(self, host: str, port: int, server_name: Optional[str] = None) -> "Connection": ...
    def local_addr(self) -> str: ...
    def close(self) -> None: ...
    async def __aenter__(self) -> "Endpoint": ...
    async def __aexit__(self, *args: Any) -> bool: ...

class Connection:
    async def open_bidi_stream(self) -> Tuple["SendStream", "RecvStream"]: ...
    async def open_uni_stream(self) -> "SendStream": ...
    async def established(self) -> bool: ...
    def remote_addr(self) -> str: ...
    def server_name(self) -> Optional[str]: ...
    def is_established(self) -> bool: ...
    def close(self, error_code: int = 0, reason: Optional[str] = None) -> None: ...

class SendStream:
    stream_id: int
    async def write(self, data: bytes) -> int: ...
    async def finish(self) -> bool: ...
    def reset(self, error_code: int) -> None: ...

class RecvStream:
    stream_id: int
    async def read(self, max_bytes: int = 65536) -> bytes: ...
    def stop(self, error_code: int) -> None: ...

class H3Server:
    def __init__(
        self,
        app: Any,
        host: str = "0.0.0.0",
        port: int = 4433,
        certfile: Optional[str] = None,
        keyfile: Optional[str] = None,
    ) -> None: ...
    async def serve(self) -> None: ...
    def shutdown(self) -> None: ...

def serve(
    app: Any,
    *,
    host: str = "0.0.0.0",
    port: int = 4433,
    certfile: Optional[str] = None,
    keyfile: Optional[str] = None,
) -> None:
    """Run an ASGI app over HTTP/3. Drop-in for uvicorn.run()."""
    ...
